export const list1_1 = [
  {
    index: 0,
    required: false,
    delete: false,
    clean: false,
    name: '水星轮',
    number: 10001,
    Cu: 0,
    Fe: 0,
    S: 0,
    SiO2: 0,
    CaO: 0,
    As: 0,
    Zn: 0,
    Pb: 0,
    MgO: 0,
    Al2O3: 0,
    H2O: 0,
    Sb: 0,
    Ni: 0,
    Bi: 0,
    Ag: 0,
    Au: 0,
    inventory: 1000,
    calculatePercentage: 0,
    inventoryBalance: ''
  },
  {
    index: 0,
    required: false,
    delete: false,
    clean: false,
    name: '莱科塔',
    number: 10002,
    Cu: 0,
    Fe: 0,
    S: 0,
    SiO2: 0,
    CaO: 0,
    As: 0,
    Zn: 0,
    Pb: 0,
    MgO: 0,
    Al2O3: 0,
    H2O: 0,
    Sb: 0,
    Ni: 0,
    Bi: 0,
    Ag: 0,
    Au: 0,
    inventory: 1000,
    calculatePercentage: 0,
    inventoryBalance: ''
  },
  {
    index: 2,
    required: false,
    delete: false,
    clean: false,
    name: '和盛',
    number: 10003,
    Cu: 0,
    Fe: 0,
    S: 0,
    SiO2: 0,
    CaO: 0,
    As: 0,
    Zn: 0,
    Pb: 0,
    MgO: 0,
    Al2O3: 0,
    H2O: 0,
    Sb: 0,
    Ni: 0,
    Bi: 0,
    Ag: 0,
    Au: 0,
    inventory: 1000,
    calculatePercentage: 0,
    inventoryBalance: ''
  },
  {
    index: 3,
    required: false,
    delete: false,
    clean: false,
    name: '方舟21',
    number: 10004,
    Cu: 0,
    Fe: 0,
    S: 0,
    SiO2: 0,
    CaO: 0,
    As: 0,
    Zn: 0,
    Pb: 0,
    MgO: 0,
    Al2O3: 0,
    H2O: 0,
    Sb: 0,
    Ni: 0,
    Bi: 0,
    Ag: 0,
    Au: 0,
    inventory: 1000,
    calculatePercentage: 0,
    inventoryBalance: ''
  },
  {
    index: 4,
    required: false,
    delete: false,
    clean: false,
    name: '江门商人',
    number: 10005,
    Cu: 0,
    Fe: 0,
    S: 0,
    SiO2: 0,
    CaO: 0,
    As: 0,
    Zn: 0,
    Pb: 0,
    MgO: 0,
    Al2O3: 0,
    H2O: 0,
    Sb: 0,
    Ni: 0,
    Bi: 0,
    Ag: 0,
    Au: 0,
    inventory: 1000,
    calculatePercentage: 0,
    inventoryBalance: ''
  },
]

export const list2_1 = [
  [
    {
      cohesion: true,
      name: '水星轮',
      number: 10001,
      Cu: 1,
      Fe: 2,
      S: 3,
      SiO2: 4,
      CaO: 5,
      As: 6,
      Zn: 7,
      Pb: 8,
      MgO: 9,
      Al2O3: 10,
      H2O: 11,
      inventory: 12,
      calculatePercentage: '',
      inventoryBalance: '',
      productionTime: 1000,
      formula: '1'
    },
    {
      cohesion: false,
      name: '莱科塔',
      number: 10002,
      Cu: 13,
      Fe: 14,
      S: 15,
      SiO2: 15,
      CaO: 15,
      As: 15,
      Zn: 15,
      Pb: 15,
      MgO: 15,
      Al2O3: 15,
      H2O: 15,
      inventory: 1000,
      calculatePercentage: '',
      inventoryBalance: '',
      productionTime: 1000,
      formula: '1'
    },
    {
      cohesion: true,
      name: '和盛',
      number: 10003,
      Cu: 16,
      Fe: 16,
      S: 16,
      SiO2: 16,
      CaO: 16,
      As: 16,
      Zn: 16,
      Pb: 16,
      MgO: 16,
      Al2O3: 16,
      H2O: 16,
      inventory: 16,
      calculatePercentage: '',
      inventoryBalance: '',
      productionTime: 1000,
      formula: '1'
    },
    {
      cohesion: false,
      name: '方舟21',
      number: 10004,
      Cu: 20,
      Fe: 20,
      S: 20,
      SiO2: 20,
      CaO: 20,
      As: 20,
      Zn: 20,
      Pb: 20,
      MgO: 20,
      Al2O3: 20,
      H2O: 20,
      inventory: 20,
      calculatePercentage: '',
      inventoryBalance: '',
      productionTime: 1000,
      formula: '1'
    },
    {
      cohesion: false,
      name: '江门商人',
      number: 10005,
      Cu: 30,
      Fe: 30,
      S: 30,
      SiO2: 30,
      CaO: 30,
      As: 30,
      Zn: 30,
      Pb: 30,
      MgO: 30,
      Al2O3: 30,
      H2O: 30,
      Sb: 30,
      Bi: 30,
      Ni: 30,
      Ag: 30,
      Au: 30,
      inventory: 30,
      calculatePercentage: '',
      inventoryBalance: '',
      productionTime: 1000,
      formula: '1'
    },
  ],
  [
    {
      delete: false,
      name: '表2项目1',
      number: 10007,
      Cu: 20,
      Fe: 20,
      S: 20,
      SiO2: 20,
      CaO: 20,
      As: 20,
      Zn: 20,
      Pb: 20,
      MgO: 20,
      Al2O3: 20,
      H2O: 20,
      inventory: 20,
      calculatePercentage: '',
      inventoryBalance: '',
      productionTime: 1000,
      formula: '2'
    },
    {
      delete: false,
      name: '表2项目2',
      number: 10008,
      Cu: 30,
      Fe: 30,
      S: 30,
      SiO2: 30,
      CaO: 30,
      As: 30,
      Zn: 30,
      Pb: 30,
      MgO: 30,
      Al2O3: 30,
      H2O: 30,
      Sb: 30,
      Bi: 30,
      Ni: 30,
      Ag: 30,
      Au: 30,
      inventory: 30,
      calculatePercentage: '',
      inventoryBalance: '',
      productionTime: 1000,
      formula: '2'
    },
    {
      delete: false,
      name: '表2项目3',
      number: 10009,
      Cu: 30,
      Fe: 30,
      S: 30,
      SiO2: 30,
      CaO: 30,
      As: 30,
      Zn: 30,
      Pb: 30,
      MgO: 30,
      Al2O3: 30,
      H2O: 30,
      Sb: 30,
      Bi: 30,
      Ni: 30,
      Ag: 30,
      Au: 30,
      inventory: 30,
      calculatePercentage: '',
      inventoryBalance: '',
      productionTime: 1000,
      formula: '2'
    },
    {
      cohesion: false,
      name: '江门商人',
      number: 10006,
      Cu: 30,
      Fe: 30,
      S: 30,
      SiO2: 30,
      CaO: 30,
      As: 30,
      Zn: 30,
      Pb: 30,
      MgO: 30,
      Al2O3: 30,
      H2O: 30,
      Sb: 30,
      Bi: 30,
      Ni: 30,
      Ag: 30,
      Au: 30,
      inventory: 30,
      calculatePercentage: '',
      inventoryBalance: '',
      productionTime: 1000,
      formula: '2'
    },
  ]
]

export const list2_2 = [

]

export const columns1_1 = [
  {
    title: '库存物料',
    dataIndex: 'name',
  },
  {
    title: 'Cu',
    dataIndex: 'Cu',
  },
  {
    title: 'Fe',
    dataIndex: 'Fe',
  },
  {
    title: 'S',
    dataIndex: 'S',
  },
  {
    title: 'SiO2',
    dataIndex: 'SiO2',
  }, {
    title: 'CaO',
    dataIndex: 'CaO',
  },
  {
    title: 'As',
    dataIndex: 'As',
  }, {
    title: 'Zn',
    dataIndex: 'Zn',
  },
  {
    title: 'Pb',
    dataIndex: 'Pb',
  },
  {
    title: 'MgO',
    dataIndex: 'MgO',
  },
  {
    title: 'Al2O3',
    dataIndex: 'Al2O3',
  },
  {
    title: 'H2O',
    dataIndex: 'H2O',
  },
  {
    title: 'Sb',
    dataIndex: 'Sb',
  },
  {
    title: 'Bi',
    dataIndex: 'Bi',
  },
  {
    title: 'Ni',
    dataIndex: 'Ni',
  },
  {
    title: 'Ag(t/g)',
    dataIndex: 'Ag',
  },
  {
    title: 'Au(t/g)',
    dataIndex: 'Au',
  }
]

export const columns1_2 = [
  {
    title: '名称',
    dataIndex: 'name',
  },
  {
    title: '批次号',
    dataIndex: 'number',
  },
  {
    title: 'Cu',
    dataIndex: 'Cu',
  },
  {
    title: 'Fe',
    dataIndex: 'Fe',
  },
  {
    title: 'S',
    dataIndex: 'S',
  },
  {
    title: 'SiO2',
    dataIndex: 'SiO2',
  }, {
    title: 'CaO',
    dataIndex: 'CaO',
  },
  {
    title: 'As',
    dataIndex: 'As',
  }, {
    title: 'Zn',
    dataIndex: 'Zn',
  },
  {
    title: 'Pb',
    dataIndex: 'Pb',
  },
  {
    title: 'MgO',
    dataIndex: 'MgO',
  },
  {
    title: 'Al2O3',
    dataIndex: 'Al2O3',
  },
  {
    title: 'H2O',
    dataIndex: 'H2O',
  },
  {
    title: 'Sb',
    dataIndex: 'Sb',
  },
  {
    title: 'Bi',
    dataIndex: 'Bi',
  },
  {
    title: 'Ni',
    dataIndex: 'Ni',
  },
  {
    title: 'Ag(t/g)',
    dataIndex: 'Ag',
  },
  {
    title: 'Au(t/g)',
    dataIndex: 'Au',
  },
  {
    title: '库存/吨',
    dataIndex: 'inventory',
  },
  {
    title: '演算比例',
    dataIndex: 'calculatePercentage',
    // editable: true
  },
  {
    title: '库存余量',
    dataIndex: 'inventoryBalance',
  },
  {
    title: '生产时间',
    dataIndex: 'productionTime',
  },
  {
    title: '调整比例',
    dataIndex: 'adjustRatio',
    editable: true,
    step: .01
  },
];

export const columns1_3 = [
  {
    title: '入炉混合料',
    dataIndex: 'name',
  },
  {
    title: 'Cu',
    dataIndex: 'Cu',
  },
  {
    title: 'Fe',
    dataIndex: 'Fe',
  },
  {
    title: 'S',
    dataIndex: 'S',
  },
  {
    title: 'SiO2',
    dataIndex: 'SiO2',
  }, {
    title: 'CaO',
    dataIndex: 'CaO',
  },
  {
    title: 'As',
    dataIndex: 'As',
  }, {
    title: 'Zn',
    dataIndex: 'Zn',
  },
  {
    title: 'Pb',
    dataIndex: 'Pb',
  },
  {
    title: 'MgO',
    dataIndex: 'MgO',
  },
  {
    title: 'Al2O3',
    dataIndex: 'Al2O3',
  },
  {
    title: 'H2O',
    dataIndex: 'H2O',
  },
  {
    title: 'Sb',
    dataIndex: 'Sb',
  },
  {
    title: 'Bi',
    dataIndex: 'Bi',
  },
  {
    title: 'Ni',
    dataIndex: 'Ni',
  },
  {
    title: 'Ag(t/g)',
    dataIndex: 'Ag',
  },
  {
    title: 'Au(t/g)',
    dataIndex: 'Au',
  },
]

export const columns3_1 = [
  {
    title: '物料分类',
    dataIndex: 'material',
    editable: true,
    formType: 'select'
  },
  {
    title: '物料编码',
    dataIndex: 'number',
    //editable: true,
  },
  {
    title: '物料名称',
    dataIndex: 'name',
    editable: true,
    formType: 'text'
  },
  {
    title: '上期结存干量(t)',
    dataIndex: 'lastBalanceDry',
    editable: true,
  },
  {
    title: '上期结存Cu(%)',
    dataIndex: 'lastBalancePercentageCu',
    editable: true,
  },
  {
    title: '上期结存Cu(t)',
    dataIndex: 'lastBalanceCu',
    editable: true,
  },
  {
    title: '上期结存Ag(g/t)',
    dataIndex: 'lastBalanceUnitageAg',
    editable: true,
  },
  {
    title: '上期结存Ag(g)',
    dataIndex: 'lastBalanceAg',
    editable: true,
  },
  {
    title: '上期结存Au(g/t)',
    dataIndex: 'lastBalanceUnitageAu',
    editable: true,
  },
  {
    title: '上期结存Au(g)',
    dataIndex: 'lastBalanceAu',
    editable: true,
  },
  {
    title: '本期收入干量(t)',
    dataIndex: 'currentIncomeDry',
    editable: true,
  },
  {
    title: '本期收入Cu(%)',
    dataIndex: 'currentIncomePercentageCu',
    editable: true,
  },
  {
    title: '本期收入Cu(t)',
    dataIndex: 'currentIncomeCu',
    editable: true,
  },
  {
    title: '本期收入Ag(g/t)',
    dataIndex: 'currentIncomeUnitageAg',
    editable: true,
  },
  {
    title: '本期收入Ag(g)',
    dataIndex: 'currentIncomeAg',
    editable: true,
  },
  {
    title: '本期收入Au(g/t)',
    dataIndex: 'currentIncomeUnitageAu',
    editable: true,
  },
  {
    title: '本期收入Au(g)',
    dataIndex: 'currentIncomeAu',
    editable: true,
  },
  {
    title: '本期结存 干量(t)',
    dataIndex: 'currentBalanceDry',
    editable: true,
  },
  {
    title: '本期结存Cu(%)',
    dataIndex: 'currentBalancePercentageCu',
    editable: true,
  },
  {
    title: '本期结存Cu(t)',
    dataIndex: 'currentBalanceCu',
    editable: true,
  },
  {
    title: '本期结存Ag(g/t)',
    dataIndex: 'currentBalanceUnitageAg',
    editable: true,
  },
  {
    title: '本期结存Ag(g)',
    dataIndex: 'currentBalanceAg',
    editable: true,
  },
  {
    title: '本期结存Au(g/t)',
    dataIndex: 'currentBalanceUnitageAu',
    editable: true,
  },
  {
    title: '本期结存Au(g)',
    dataIndex: 'currentBalanceAu',
    editable: true,
  },
  {
    title: '本期使用 干量(t)',
    dataIndex: 'currentCostDry',
    editable: true,
  },
  {
    title: '本期使用Cu(t)',
    dataIndex: 'currentCostCu',
    editable: true,
  },
  {
    title: '本期使用Ag(g)',
    dataIndex: 'currentCostAg',
    editable: true,
  },
  {
    title: '本期使用Au(g)',
    dataIndex: 'currentCostAu',
    editable: true,
  },

]


